// <auto-generated />
namespace OrdersAssignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addeddeletedflagtomodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addeddeletedflagtomodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201710051954479_Added deleted flag to models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
